# Generated by Django 4.2 on 2023-04-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
